esphome:
  name: esphome-web-b601d0
  friendly_name: Bentobox P1S v2
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  networks: 
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bentobox v2 Fallback Hotspot"
    password: "E51NjRX0iGZr"

captive_portal:
 
output:
  - platform: gpio
    pin: GPIO0
    id: "out_1"

fan:
  - platform: binary
    name: "Bentobox Fans"
    id: filter_fans
    output: out_1

light:
  - platform: status_led
    name: "Status LED"
    id: esp_status_led
    icon: "mdi:alarm-light"
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO8
      #inverted: false
      inverted: True